### ISSUE TITLE
申请导一份数据是这样就可以了吗

### ISSUE THREAD

**Issue by yutouyes** [Ricky-Hao/bili_comment#1]
想要一份库主（这个称呼不知道可不可以）抓的数据，是这样开个issue就OK了嘛？肥肠感谢！
Data please. Thank you very much.

**Comment by Ricky-Hao** [comment]
具体明确下需要哪些部分数据吧，不然文件好大。
比如指定下时间段，和哪个up的。

**Comment by yutouyes** [comment]
> 具体明确下需要哪些部分数据吧，不然文件好大。
> 比如指定下时间段，和哪个up的。

4月1日到现在的崩坏3第一偶像和崩坏3的数据，这样

**Comment by Ricky-Hao** [comment]
[aichan.7z](https://mega.nz/file/Wx5GBSKL#4JP3qRIM11-cjJO8JnijHZ9ig5__nmj-IuEv6BznNBc)
[bh3.7z](https://mega.nz/file/rtgCFDwQ#nHYH0MS32gXwbGja6jULBn_K-KRfVIGQsZLSOoo2W4U)
